# SAM 설정 파일
version = 0.1

[default.build.parameters]
cached = true
parallel = true

[dev.deploy.parameters]
stack_name = "playground-dev"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
template = "template-dev.yaml"
resolve_image_repos = true
resolve_s3 = true

[prod.deploy.parameters]
stack_name = "playground-prod"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
template = "template-prod.yaml"
resolve_s3 = true

[dev-jar.deploy.parameters]
stack_name = "playground-dev-jar"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
template = "template-dev-jar.yaml"
resolve_image_repos = true
resolve_s3 = true
